### ISSUE TITLE
片名里面出现冒号的时候会重命名失败

### ISSUE THREAD

**Issue by shyujiaxin** [junerain123/JAV-Scraper-and-Rename-local-files#11]
>第1个失败！发生错误，如一直在该影片报错请截图并联系作者：\\MAAN-055 【同僚同士でエアーSEX！】同じ職場で働く男女の意識調査！(はせ30歳 ゆき25歳)もし男女意識.mp4
Traceback (most recent call last):
  File "suren.py", line 434, in <module>
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\AD\\JP\\MAAN-055 【同僚同士でエアーSEX！】同じ職場で働く男 女の意識調査！(はせ30歳 ゆき25歳)もし男女意識.mp4' -> 'D:\\AD\\JP\\MAAN-055 【同僚同士でエアーSEX！】同じ職場で働く男女 の意識調査！(はせ/30歳 ゆき/25歳)もし男女意識.mp4'

    >第2个失败！发生错误，如一直在该影片报错请截图并联系作者：\\MIUM-120 私立パコパコ女子大学 女子大生とトラックテントで即ハメ旅 Report.014見た目清楚なSランク.mp4
Traceback (most recent call last):
  File "suren.py", line 434, in <module>
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'D:\\AD\\JP\\MIUM-120 私立パコパコ女子大学 女子大生とトラック テントで即ハメ旅 Report.014見た目清楚なSランク.mp4' -> 'D:\\AD\\JP\\MIUM-120 私立パコパコ女子大学 女子大生とトラックテントで即ハメ旅 Report.014:見た目清楚なSランク.mp4'

**Comment by junerain123** [comment]
现在已经解决了这些问题，感谢！
