### ISSUE TITLE
是MIT License吗?

### ISSUE THREAD

**Issue by ddd354** [junerain123/JAV-Scraper-and-Rename-local-files#23]
希望能注明具体的License / 是否为MIT许可证.

**Comment by junerain123** [comment]
![image](https://user-images.githubusercontent.com/44168897/71539305-3b3d3180-2975-11ea-8cde-a6c5605de352.png)
![image](https://user-images.githubusercontent.com/44168897/71539693-18ae1700-297b-11ea-95b0-9c0856c0cccd.png)
看了几张图，才大概了解许可证是啥，以前只知道gpl。
现在在readme注明了，使用mit许可证，允许你修改、发布、商用、闭源。
