### ISSUE TITLE
貌似不支持legsjapan

### ISSUE THREAD

**Issue by SeanChengN** [junerain123/JAV-Scraper-and-Rename-local-files#32]
https://www.legsjapan.com/en/

**Comment by junerain123** [comment]
这个网站是这些影片的官网，还是什么？我找不到车牌，点进去就要收费。

**Comment by SeanChengN** [comment]
> 这个网站是这些影片的官网，还是什么？我找不到车牌，点进去就要收费。

😂的确是需要会员才能看见番号，没调查清楚，抱歉
